INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Tiger Nixon', '123456',1, 'System Architect@qq.com', '170600', 'System Architect');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Garrett Winters', '123456',1, 'Accountant@qq.com', '170500', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Ashton Cox', '123465',1, 'Junior Technical Author@qq.com', '86000', 'Junior Technical Author');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Cedric Kelly', '123465',1, 'Senior Javascript Developer@qq.com', '433060', 'Senior Javascript Developer');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Airi Satou', '123456',1, 'Accountant@qq.com', '162700', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Brielle Williamson', '123456',1, 'Integration Specialist@qq.com', '372000', 'Integration Specialist');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Herrod Chandler', '123456',1, 'Sales Assistant@qq.com', '137500', 'Sales Assistant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Ashton Cox', '123456',1, 'Junior Technical Author@qq.com', '86000', 'Junior Technical Author');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Cedric Kelly', '123465',1, 'Senior Javascript Developer@qq.com', '433060', 'Senior Javascript Developer');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Airi Satou', '123456',1, 'Accountant@qq.com', '162700', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Brielle Williamson', '123456',1, 'Integration Specialist@qq.com', '372000', 'Integration Specialist');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Herrod Chandler', '123456',1, 'Sales Assistant@qq.com', '137500', 'Sales Assistant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Tiger Nixon', '123456',1, 'System Architect@qq.com', '320800', 'System Architect');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Garrett Winters', '123456',1, 'Accountant@qq.com', '170500', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Ashton Cox', '123465',1, 'Junior Technical Author@qq.com', '86000', 'Junior Technical Author');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Cedric Kelly', '123465',1, 'Senior Javascript Developer@qq.com', '433060', 'Senior Javascript Developer');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Airi Satou', '123456',1, 'Accountant@qq.com', '162700', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Brielle Williamson', '123456',1, 'Integration Specialist@qq.com', '372000', 'Integration Specialist');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Herrod Chandler', '123456',1, 'Sales Assistant@qq.com', '137500', 'Sales Assistant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Ashton Cox', '123456',1, 'Junior Technical Author@qq.com', '86000', 'Junior Technical Author');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Cedric Kelly', '123465',1, 'Senior Javascript Developer@qq.com', '433060', 'Senior Javascript Developer');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Airi Satou', '123456',1, 'Accountant@qq.com', '162700', 'Accountant');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Brielle Williamson', '123456',1, 'Integration Specialist@qq.com', '372000', 'Integration Specialist');
INSERT INTO `es_member`(`member_name`, `member_password`, `role_id`, `email`, `phone`, `memo`)  VALUES ('Herrod Chandler', '123456',1, 'Sales Assistant@qq.com', '137500', 'Sales Assistant');
